%% STEP 1
clear;
clc;

[D,E,F]=xlsread("..\basininfo.xlsx",'EFaverage'); % derived from the Emission Factors dataset (DOI:10.1038/s43016-021-00384-9).
F(1,:)=[];

PathRoot='..\N\';
Pathout='..\EM\'; % obtained from results of GCAM model.
listdir=dir(fullfile(Pathout));
fileNum=size(listdir,1);

for kk=3:fileNum

    listdir(kk).name;
    [A,B,C]=xlsread([Pathout,listdir(kk).name],'sheet1');
    listc=["Corn","Wheat","Rice","othercrop"];

    for c=1:length(listc)
        G={};
        G=C(find(strcmp(C(:,1),listc(c)))',:);

        for j=1:235
            k=find(strcmp(G(:,2),F(j,7)))';
            if cell2mat(F(j,2+c))==-9999
                G(k,5)=num2cell(0);
                G(k,6)=num2cell(0);
            else
                G(k,5)=num2cell(cell2mat(G(k,3))./cell2mat(F(j,2+c)));
                G(k,6)=num2cell(cell2mat(G(k,4))./cell2mat(F(j,2+c)));
            end
        end

        result = [{'sector','basin','em2050','em2100','n2050','n2100'}; G];
        xlswrite([PathRoot,listdir(kk).name(1:3),'_N_',num2str(c),'.xls'], result);
    end

end

%% STEP 2
clear;
clc;

[glu,R]=geotiffread("..\glu005.tif"); % a template file in geotiff format containing 2780*7206 grids.
[D,E,F]=xlsread("..\basininfo.xlsx",'id');

glu=double(glu);

PathRoot='..\N\';
Pathout='..\NTIF\';
listdir=dir(fullfile(PathRoot));
fileNum=size(listdir,1);

for kk=3:fileNum

    [A,B,C]=xlsread([PathRoot,listdir(kk).name],'sheet1');
    C(1,:)=[];
    c=str2double(listdir(kk).name(7));

    cc=size(C);
    for i=1:cc(1)
        C(i,7)=F(strcmp(F(:,4),C(i,2)),1);
    end

    glu2050=zeros(2780,7206);
    glu2100=zeros(2780,7206);

    for i=1:2780
        for k=1:7206
            if glu(i,k)==255
                glu2050(i,k)=NaN;
                glu2100(i,k)=NaN;
            else
                aa=find(cell2mat(C(:,7))==glu(i,k));
                if isempty(aa)
                    glu2050(i,k)=NaN;
                    glu2100(i,k)=NaN;
                else
                    glu2050(i,k)=cell2mat(C(aa,5))*10^12*100;
                    glu2100(i,k)=cell2mat(C(aa,6))*10^12*100;
                end
            end
        end
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename2050=[Pathout,'s',listdir(kk).name(1:3),'_2050_',num2str(c),'.tif'];
    geotiffwrite(filename2050,glu2050,ref);
    filename2100=[Pathout,'s',listdir(kk).name(1:3),'_2100_',num2str(c),'.tif'];
    geotiffwrite(filename2100,glu2100,ref);

end

%% STEP 3
clear;
clc;

Path1='..\NTIF\';
Path2='..\gcamld\TIF3\'; % land cover generated by GCAM and Demeter models.
Path4='..\gcamld\ldusall\'; % sum of land cover for each crop category.
Pathout='..\N-spt\';

listdir1=dir(fullfile(Path1));
listdir2=dir(fullfile(Path2));
listdir4=dir(fullfile(Path4));
fileNum=size(listdir1,1);

for kk=3:fileNum

    [A,R]=geotiffread([Path1,listdir1(kk).name]);
    [B,R]=geotiffread([Path2,listdir2(kk).name]);
    [BB,R]=geotiffread([Path4,listdir4(kk).name]);

    C=zeros(2780,7206);

    for i=1:2780
        for j=1:7206
            C(i,j)=(A(i,j).*B(i,j))./BB(i,j);
        end
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    C(isnan(C))=0;

    filename=[Pathout,'n_',listdir1(kk).name];
    geotiffwrite(filename,C,ref);

end

%% STEP 4
clear;
clc;

Path1='..\N-spt\';
Path3='..\EF\'; % obtained from the Emission Factors dataset (DOI:10.1038/s43016-021-00384-9).
Pathout='..\N2OTIF\';

listdir1=dir(fullfile(Path1));
listdir3=dir(fullfile(Path3));
fileNum=size(listdir1,1);

for kk=3:fileNum

    [A,R]=geotiffread([Path1,listdir1(kk).name]);
    C=zeros(2780,7206);

    switch mod(kk-2,4)
        case 1
            [CC,R]=geotiffread([Path3,listdir3(3).name]);
            CC(isnan(CC))=0;
        case 2
            [CC,R]=geotiffread([Path3,listdir3(4).name]);
            CC(isnan(CC))=0;
        case 3
            [CC,R]=geotiffread([Path3,listdir3(5).name]);
            CC(isnan(CC))=0;
        otherwise
            [CC,R]=geotiffread([Path3,listdir3(6).name]);
            CC(isnan(CC))=0;
    end

    for i=1:2780
        for j=1:7206
            C(i,j)=A(i,j).*CC(i,j)/100;
        end
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename=[Pathout,'N2Onew_',listdir1(kk).name];
    geotiffwrite(filename,C,ref);

end

%% STEP 5
clear;
clc;

[glu,R]=geotiffread("..\glu005.tif");
glu=double(glu);
Path2='..\N2OTIF\';

listdir2=dir(fullfile(Path2));
fileNum=size(listdir2,1);

for kk=3:fileNum

    [B,R]=geotiffread([Path2,listdir2(kk).name]);
    B=flipud(B);
    BB=B;

    for i=1:235
        BB(glu==i)=sum(B(find(glu==i)),'omitmissing');
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename=['..\N2OTIF_sum\N2Osum_',listdir2(kk).name];
    geotiffwrite(filename,BB,ref);

end

%% STEP 6
clear;
clc;

Path1='..\N2OTIF\';
Path3='..\N2OTIF_sum\';
Pathout='..\N2Opercent\';

listdir1=dir(fullfile(Path1));
listdir3=dir(fullfile(Path3));
fileNum=size(listdir1,1);

for kk=3:fileNum

    [A,R]=geotiffread([Path1,listdir1(kk).name]);
    C=zeros(2780,7206);
    [CC,R]=geotiffread([Path3,listdir3(kk).name]);

    for i=1:2780
        for j=1:7206
            C(i,j)=A(i,j)./CC(i,j);
        end
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename=[Pathout,'percent_',listdir1(kk).name];
    geotiffwrite(filename,C,ref);

end

%% STEP 7
clear;
clc;

[glu,R]=geotiffread("..\glu005.tif");
[D,E,F]=xlsread("..\basininfo.xlsx",'id');
glu=double(glu);

PathRoot='..\N\';
Pathout='..\N2OTIF_orig\';
listdir=dir(fullfile(PathRoot));
fileNum=size(listdir,1);

for kk=3:fileNum

    [A,B,C]=xlsread([PathRoot,listdir(kk).name],'sheet1');
    C(1,:)=[];
    c=str2double(listdir(kk).name(7));

    cc=size(C);
    for i=1:cc(1)
        C(i,7)=F(strcmp(F(:,4),C(i,2)),1);
    end

    glu2050=zeros(2780,7206);
    glu2100=zeros(2780,7206);

    for i=1:2780
        for k=1:7206
            if glu(i,k)==255
                glu2050(i,k)=NaN;
                glu2100(i,k)=NaN;
            else
                aa=find(cell2mat(C(:,7))==glu(i,k));
                if isempty(aa)
                    glu2050(i,k)=NaN;
                    glu2100(i,k)=NaN;
                else
                    glu2050(i,k)=cell2mat(C(aa,3))*10^12;
                    glu2100(i,k)=cell2mat(C(aa,4))*10^12;
                end
            end
        end
    end

    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename2050=[Pathout,'s',listdir(kk).name(1:3),'_2050_',num2str(c),'.tif'];
    geotiffwrite(filename2050,glu2050,ref);
    filename2100=[Pathout,'s',listdir(kk).name(1:3),'_2100_',num2str(c),'.tif'];
    geotiffwrite(filename2100,glu2100,ref);

end

%% STEP 8
clear;
clc;

Path1='..\N2Opercent\';
Path3='..\N2OTIF_orig\';
Pathout='..\final\';

listdir1=dir(fullfile(Path1));
listdir3=dir(fullfile(Path3));
fileNum=size(listdir1,1);

for kk=3:fileNum

    [A,R]=geotiffread([Path1,listdir1(kk).name]);
    A(isnan(A))=0;
    C=zeros(2780,7206);
    D=flipud(A);
    [CC,R]=geotiffread([Path3,listdir3(kk).name]);
    CC(isnan(CC))=0;

    for i=1:2780
        for j=1:7206
            C(i,j)=D(i,j).*CC(i,j);
        end
    end

    C(find(C==0))=NaN;
    ref=georasterref('RasterSize',[2780,7206],'Latlim',[-54.9750,83.6750],'Lonlim',[-179.9700,179.9700]);
    filename=[Pathout,'finalnew_',listdir1(kk).name]; % the final emission files.
    geotiffwrite(filename,C,ref);

end
